### ISSUE TITLE
Unable to connect to Dynamics 365 CE Online CRM Instance (TLS 1.2 required)

### ISSUE THREAD

**Issue by slautebach** [Adoxio/dynamics-portal-companion-app#6]
Since December likely after a change from Microsoft, I am unable to get xRM Portals Community Edition to connect to a Dynmaics 365 CE Online CRM Instance.

I get the following error:

> The Organization Service URL is invalid. Metadata contains a reference that cannot be resolved: 'https://researchportal.crm3.dynamics.com/XRMServices/2011/Organization.svc?wsdl&sdkversion=8.2'. The underlying connection was closed: An unexpected error occurred on a send. Authentication failed because the remote party has closed the transport stream

![image](https://user-images.githubusercontent.com/4151954/34885488-236f40b8-f78e-11e7-9982-871d30ec6174.png)

After some research I found these these links that hit to the problem:
https://blogs.msdn.microsoft.com/crm/2017/09/28/updates-coming-to-dynamics-365-customer-engagement-connection-security/
https://community.dynamics.com/crm/f/117/t/263162

It appears the MS is now requiring online servers to connect with a minimum of TLS 1.2.

I have a potential fix as recommended from a forum to set 
```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;
```
that I will submit a PR for.  I have tested connectivity to online and an on premise instance of CRM and they both work with the code change.

**Comment by amervitz** [comment]
This issue is in the wrong project. Also, the upgrade to .NET 4.7 was supposed to make TLS 1.2 be used by default, so we need to research why that isn't happening before deciding whether to use this change you've submitted.

**Comment by slautebach** [comment]
My apologies, I thought I was filing this against xRM Portals.  I will file it there.
